services:
  - type: web
    name: my-service
    env: python
    plan: starter
    buildCommand: "./setup.sh && pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
    buildScript:
      - name: Install ZBar dependencies
        script: ./setup.sh

  - type: cron
    name: my-cron-job
    cronCommand: "python cron_job.py"
    schedule: "0 0 * * *"
    env: python
    plan: starter
    buildCommand: "./setup.sh && pip install -r requirements.txt"
    startCommand: "python cron_job.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
